// <auto-generated />
using System;
using AnnConn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnnConn.Migrations
{
    [DbContext(typeof(AnnContext))]
    [Migration("20181116021625_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnnConn.Models.Collaborators", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyProperty");

                    b.Property<string>("email");

                    b.Property<string>("fullName");

                    b.Property<string>("gender");

                    b.Property<DateTime>("joinDate");

                    b.Property<string>("office");

                    b.Property<string>("password");

                    b.HasKey("ID");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("AnnConn.Models.Contracts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollaboratorsID");

                    b.Property<string>("MyProperty");

                    b.HasKey("ID");

                    b.HasIndex("CollaboratorsID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AnnConn.Models.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollaboratorsID");

                    b.Property<int>("cNumber");

                    b.Property<string>("ch");

                    b.Property<double>("charges");

                    b.Property<string>("condition");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("note");

                    b.Property<int>("pNumber");

                    b.Property<string>("phone");

                    b.Property<string>("policy");

                    b.Property<double>("price");

                    b.Property<double>("totals");

                    b.HasKey("ID");

                    b.HasIndex("CollaboratorsID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AnnConn.Models.Contracts", b =>
                {
                    b.HasOne("AnnConn.Models.Collaborators")
                        .WithMany("contracts")
                        .HasForeignKey("CollaboratorsID");
                });

            modelBuilder.Entity("AnnConn.Models.Customers", b =>
                {
                    b.HasOne("AnnConn.Models.Collaborators")
                        .WithMany("customers")
                        .HasForeignKey("CollaboratorsID");
                });
#pragma warning restore 612, 618
        }
    }
}
