// <auto-generated />
using System;
using AnnConn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnnConn.Migrations
{
    [DbContext(typeof(AnnContext))]
    [Migration("20181123063813_fu")]
    partial class fu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnnConn.Models.Administrator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("fullName");

                    b.Property<string>("password");

                    b.HasKey("ID");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("AnnConn.Models.Appoinment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contract");

                    b.Property<string>("Customer")
                        .IsRequired();

                    b.Property<int?>("SaleID");

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("product");

                    b.Property<string>("sale");

                    b.HasKey("ID");

                    b.HasIndex("SaleID");

                    b.ToTable("Appoinment");
                });

            modelBuilder.Entity("AnnConn.Models.Collaborators", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("fullName");

                    b.Property<string>("gender");

                    b.Property<DateTime>("joinDate");

                    b.Property<string>("office");

                    b.Property<string>("password");

                    b.HasKey("ID");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("AnnConn.Models.Contracts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollaboratorsID");

                    b.Property<string>("c1");

                    b.Property<string>("c2");

                    b.Property<string>("c3");

                    b.Property<string>("code");

                    b.Property<string>("collabor");

                    b.Property<string>("condition");

                    b.Property<string>("customer");

                    b.Property<DateTime>("d1");

                    b.Property<DateTime>("d2");

                    b.Property<DateTime>("d3");

                    b.Property<int>("day1");

                    b.Property<int>("day2");

                    b.Property<int>("day3");

                    b.Property<DateTime>("dl1");

                    b.Property<DateTime>("dl2");

                    b.Property<DateTime>("dl3");

                    b.Property<string>("email");

                    b.Property<double>("f1");

                    b.Property<double>("f2");

                    b.Property<double>("f3");

                    b.Property<string>("note");

                    b.Property<DateTime>("pDate");

                    b.Property<string>("phone");

                    b.Property<string>("r1");

                    b.Property<string>("r2");

                    b.Property<string>("r3");

                    b.Property<string>("s1");

                    b.Property<string>("s2");

                    b.Property<string>("s3");

                    b.HasKey("ID");

                    b.HasIndex("CollaboratorsID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AnnConn.Models.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollaboratorsID");

                    b.Property<int>("cNumber");

                    b.Property<string>("ch");

                    b.Property<double>("charges");

                    b.Property<string>("condition");

                    b.Property<string>("email");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("note");

                    b.Property<DateTime>("pDate");

                    b.Property<int>("pNumber");

                    b.Property<string>("phone")
                        .IsRequired();

                    b.Property<string>("policy");

                    b.Property<double>("price");

                    b.Property<string>("q4a");

                    b.Property<bool>("q5a");

                    b.Property<bool>("q5b");

                    b.Property<bool>("q5c");

                    b.Property<bool>("q5d");

                    b.Property<bool>("q6a");

                    b.Property<bool>("q6b");

                    b.Property<bool>("q6c");

                    b.Property<bool>("q7a");

                    b.Property<bool>("q7b");

                    b.Property<bool>("q7c");

                    b.Property<bool>("q7d");

                    b.Property<bool>("q7e");

                    b.Property<bool>("q7f");

                    b.Property<bool>("q7g");

                    b.Property<bool>("q7h");

                    b.Property<bool>("q7i");

                    b.Property<bool>("q7j");

                    b.Property<bool>("q7k");

                    b.Property<bool>("q7l");

                    b.Property<bool>("q7m");

                    b.Property<string>("supporter");

                    b.Property<double>("totals");

                    b.HasKey("ID");

                    b.HasIndex("CollaboratorsID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AnnConn.Models.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("display");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("info");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("pass")
                        .IsRequired();

                    b.Property<string>("phone")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("sale");
                });

            modelBuilder.Entity("AnnConn.Models.Appoinment", b =>
                {
                    b.HasOne("AnnConn.Models.Sale")
                        .WithMany("meetings")
                        .HasForeignKey("SaleID");
                });

            modelBuilder.Entity("AnnConn.Models.Contracts", b =>
                {
                    b.HasOne("AnnConn.Models.Collaborators")
                        .WithMany("contracts")
                        .HasForeignKey("CollaboratorsID");
                });

            modelBuilder.Entity("AnnConn.Models.Customers", b =>
                {
                    b.HasOne("AnnConn.Models.Collaborators")
                        .WithMany("customers")
                        .HasForeignKey("CollaboratorsID");
                });
#pragma warning restore 612, 618
        }
    }
}
